### PR TITLE
fix timestamp nl_nl

### PR DESCRIPTION
**Pull request by JimButseraen**
Tested with real data this time.

### CODE REVIEW

**Comment by ownaginatious** [comment]
Ah, thanks for catching that :+1:

**Comment by ownaginatious** [comment]
Fixed version is up now on PyPI: `0.8.post30`

**Comment by JimButseraen** [comment]
Thanks, can I ask you something concerning the csv-files? There is always an empty line between each result, where can I change this as I'm new to Python programming I couldn't directly locate it.

**Comment by ownaginatious** [comment]
That shouldn't be the case. What program are you opening the CSV file with?

**Comment by JimButseraen** [comment]
Excel, same case in Notepad++
Could this be related to the fact I'm using Windows?

**Comment by ownaginatious** [comment]
Ah, looks like it's because of the CSV default line termination (`\r\n`). I believe UNIX systems ignore `\r`. Windows was supposed to historically ignore `\n` I think, but maybe that's been changed? I changed the line terminator to `\n` by default and just pushed a new version to PyPI (`0.8.post31`). Let me know if that fixes it :+1:

**Comment by JimButseraen** [comment]
Unfortunately the issue remains.
image

**Comment by JimButseraen** [comment]
It's working now, I cloned the Github repo and it's fine now.
My apologies for the inconvenience.

**Comment by ownaginatious** [comment]
Ah, cool. Thanks for pointing out the issue :+1: Glad to have people testing things on Windows.

**Pull request merged**
