### PR TITLE
Added slovenian-style timestamp

### PR DESCRIPTION
**Pull request by PhpXp**

### CODE REVIEW

**Comment by ownaginatious** [comment]
Thanks! Exact type of PR I was hoping for :)

Could you add a test [here](https://github.com/ownaginatious/fbchat-archive-parser/blob/master/tests/test_timestamps.py)?

**Comment by Planbos** [comment]
Can you please help me. I am not experienced and I am having some issues. I have been downloaded zip and add values in time.py, but now I don t know how to install or update this package. Previously I installed with pip, but those changes are not commited there.

**Comment by ownaginatious** [comment]
Are you trying to add support for some other locale?

Here are general development guidelines for most Python projects.

Ideally you should fork this repository and then clone it to your computer. Once you have cloned it, you can change to the root of the project and run `virtualenv venv && ./venv/bin/activate`. This will prepare a virtual environment for development. You may need to install `virtualenv` first using something like `sudo pip install virtualenv`.

Following that, you run `python ./setup.py develop`, which installs this app into your virtual environment transparently via symlinks. From then on, any changes you make to the code will be reflected when you run `fbcap` with the virtual environment activated. You can run `python ./setup.py test` to ensure your changes (probably?) didn't break the project.

After you're satisfied, push your branch to your fork and then make a PR to merge it in :)

**Comment by Planbos** [comment]
Great, thx. 
But I am having another question. I am also using some other similar script which is great for what I need, but not always working properly so I am looking for alternatives and your script is very good alternative, but... This other script I mention split conversations each in separate file. Can this feature be added to your script somehow? 
I don t want to be annoying, but maybe you are looking for some ideas for improving your already great work and this maybe is good idea!? 
Thx again and greetings from Slovenia!

**Comment by ownaginatious** [comment]
@Planbos That's actually a great idea! I was planning on doing something similar before, but forgot about it. Would you mind making a new issue in the GitHub project with your suggestion? I will try to implement it promptly.

**Comment by ownaginatious** [comment]
@PhpXp merged. I just added tests myself :+1: new version with Slovenian support is available (`0.9.post8`).

**Pull request merged**
